all:
  vars:
    ansible_user: kare
    ansible_ssh_private_key_file: /home/kare/.ssh/id_rsa
  children:
    k8s_hosts:
      children:
        k8s_masters:
          hosts:
            k8s-master-01.phantasia.com:
              ansible_host: 10.0.10.100
        k8s_workers:
          hosts:
            k8s-worker-01.phantasia.com:
              ansible_host: 10.0.10.101
            k8s-worker-02.phantasia.com:
              ansible_host: 10.0.10.102

